# Site settings

title: Figma Resources

# we don't use url from here because all pages will cause problms when deploying in different environments (GHP, Netlify ...). 
# we use it from environment varibles ENV["DEPLOY_PROD_BASE_URL"]. this is still here just to be aware of the way we use it
# description: ""
#url: "https://figmares.innohub.space"

# we don't use description from here because all pages will have the same <meta name="description" ...>. 
# we add it dynamically in head_custom.html. this is still here just to be aware of the way we use it
# description: ""

# Build settings
# THEME CAN BE THE LAST AS BELOW IF DEPLOY TO GHP FROM ACTION
theme: just-the-docs

# THEME SOULD BE AS BELOW IF DEPLOY TO GHP FROM BRANCH
#remote_theme: just-the-docs/just-the-docs@v0.8.0 # it works only with remote_theme. as of April 2024, v0.8.0 is the latest that works

#plugins:
#  - jekyll-feed # activate only if the site has posts

# to be ensure that inline md styles such as {:width="123px"} are processed well
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
  parse_block_html: true

# DEFAULT EXCLUDES (SHOWN HERE JUST TO BE AWARE OF THEM)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - tools/
  - tools_py/
  - tools_sh/
  - check
  - test
  - netlify.toml
  - CNAME
  - LICENSE
  - README.md
  - serve
  - serve-rack
  - config.ru
  - .github/
  - doc-raw-contents/
  - doc-change-log/
  - _data/
  - _plugins/
  - _sass/custom/*.css
  - assets/*.scss
  - .env
  - assets/config/ # excluding from build because may generate infinite build loop. copied to _site with a site:post_write hook
  - unused/

aux_links:
  "GitHub":
    - "//github.com/pmc-community/figma"
  "About":
    - "//pmc-expert.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# algolia search has priority even if search_enabled=true. see buildConfig.algoliaSearch
search_enabled: true

# heading anchors must be false because it generates a weird effect of showing huge blue anchors 
# when loading the page and until the page is loaded. nevertheless, page ToC is good and enough
heading_anchors: false

# define the folder where jekyll will look for collection, otherwise will look in the root folder
collections_dir: doc-contents

# MARKER COLLECTIONS START
collections:
  collection-1:
    permalink: "/:collection/:path"
    output: true
  collection-2:
    permalink: "/:collection/:path"
    output: true
  tools:
    permalink: "/:collection/:path"
    output: true

# see https://just-the-docs.com/docs/configuration/#document-collections
just_the_docs:
  collections:
    collection-1:
      name: Collection One
      nav_fold: true
    collection-2:
      name: Collection Two
      nav_fold: true
    tools:
      name: Tools
      nav_fold: true
# MARKER COLLECTIONS END
