# Site settings

title: Figma Resources
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Plugin Templates | Plugins | Design Systems
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.8.0

#plugins:
#  - jekyll-feed # activate only if the site has posts

# DEFAULT EXCLUDES (SHOWN HERE JUST TO BE AWARE OF THEM)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

aux_links:
  "GitHub":
    - "//github.com/pmc-community/figma"
  "About us":
    - "//pmc-expert.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# we go with agolia, otherwise set to true or remove it (true is default)
search_enabled: false

# site vars (nested)
siteVars:
  siteTestBadge: '[![](https://img.shields.io/badge/System%20Analysis-YES-1478B6?style=for-the-badge&logo=react)](#)'
  siteTestVar: site test variable

# site configuration
# content markers
siteConfig:
  extContentMarkers:
    startExposedSection: '<!-- START_EXPOSED_SECTION -->'
    endExposedSection: '<!-- END_EXPOSED_SECTION -->'

# heading anchors must be false because it generates a weird effect of showing huge blue anchors 
# when loading the page and until the page is loaded. nevertheless, page ToC is good and enough
heading_anchors: false