"/":
  enabled: true
  startPermalink: "/intro/"
  sections:
    header_section:
      title: "Figma Resources Documentation"
      text: "Learn how to use the resources built for Figma. These resources includes templates for Figma plugins and much more. FEATURED: React based template for multi-page figma plugin."
      startBtnText: "Overview"
      featuredMedia: "<img width=\"600\" height=\"auto\" src=\"assets/img/home-600.webp\" alt=\"Figmares by PMC\">"
    collections_section:
      enabledInHome: true
      except: ["posts"] # collection name must be the one from _config.yml[collections]
      itemsToShow: 5
      collectionStartBtnText: "Start here"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
    mostRecentAndPopular_section:
      recentFilesToShow: 3
      allDocsBtnText: "Documents"
      allCatsBtnText: "Categories"
      allTagsBtnText: "Tags"
      buttonsClass: "btn-warning"
      buttonsTextClass: "text-dark"
    stats_section:
      allDocsBtnText: "All docs"
      savedDocsBtnText: "Saved docs"
      catsBtnText: "Categories"
      pagesWithCustomsCatsBtnText: "Documents"
      tagsBtnText: "Tags"
      buttonsClass: "btn-primary"
      buttonsTextClass: "text-light"
      buttonsIcon: "bi-arrow-right"