# site configuration
extContentMarkers:
  startExposedSection: '<!-- START_EXPOSED_SECTION -->'
  endExposedSection: '<!-- END_EXPOSED_SECTION -->'
algoliaSearch:
  appId: 'LU8ABE5OK9'
  apiKey: '93c6d0120f05c7d6a1fe3136c0122626'
  indexName: 'figmares-innohub'
  container: '#docsearch'
  debug: false
  maxResultsPerGroup: 20
feedbackForm:
  container: '#docFeedbackForm'
pageToc:
  tocContainer: '#toc_container'
  toc: '#toc'
  tocLoadedEvent: 'page_toc_loaded'
  scrollSpyBase: 'body'
  desktop:
    referenceContainer: '.main-content'
    offsetFromHeader: 25
    offsetFromReferenceContainer: 100
    leftSideBar: '.side-bar'
colSchemaCorrections:
  elementsWithBackgroundAffected: 'body'
  backgroundColorOnElementsAffected:
    light: '#fff'
    dark: '#27262b'
  elementsWithTextAffected: 'body, p, ul li, ol li, li a'
  textColorOnElementsAffected:
    light: '#000'
    dark: '#dee2e6'
  elementsWithBorderTopAffected: '.site-footer'
  borderTopOnElementsAffected:
    light: '1px solid #eeebee'
    dark: '1px solid #44434d'
goToTopBtn:
  btnContainer: '.main'
  # don't forget to escape double quotes
  content: '<div id=\"ihs_go_to_top_btn\"><img src=\"/assets/img/goToTop.png\" loading=\"lazy\" alt=\"tick-circle\"></div>'
  topOfPageMarker: '<div id =\"ihs_top_of_page\"></div>'
  topOfPageId: '#ihs_top_of_page'
  btnId: '#ihs_go_to_top_btn'
  topOfPageContainer: '.main-content-wrap'
externalContent:
  containerToIncludeExternalContent: '.main-content main'
themeSwitch:
  cookie: 'JTDThemeCookie'
  btnContent: '<img id=\"themeSwitcher\" class=\"themeSwitcher mx-2\" src=\"/assets/img/icon-dark-mode-100.png\" />'
  btnContainer: '.aux-nav-list'
  append: false
  btnId: '#themeSwitcher'
siteFooter:
  container: '.site-footer'
  rows:
    - content: '<div class=\"footer_first_row\"><a href=\"https://innohub.space/eng/terms-of-service/\" target=_blank>Terms</a> | <a href=\"https://innohub.space/eng/privacy/\" target=_blank>Privacy</a> | <a href=\"https://innohub.space/eng/cookie-policy/\" target=_blank>Cookies</a></div>'
    - content: '<div class=\"footer_first_row\">Copyright <a href=\"https://pmc-expert.com\" target=_blank>PMC</a></div>'
headerAboveContent:
  headerID: '#main-header'
  offsetWhenScroll: 20
headerAboveSideBar:
  logo: '<a href=\"/\"><img class = \"site_logo\" src=\"/assets/img/logo.png\" /></a>'
  container: '.site-header'
layouts:
    contentArea:
      mainContainer: '.main-content-wrap'
      contentContainer: '.main-content main'
      desktop:
        padding: 'px-5'
        widthOnHome: '100%'
toBeRemovedAfterLoad:
  - "script": # selector for the element to be removed, in the form of tag, .class, #id
    - "externalContent" # each selector[siteAttr = ...] will be removed
  - "h1":
    - "testAttr"
    - "testAttr_1"
marker404: "site-this-is-404-page" # should be allocated as id to one element in 404.html