# HEADS UP!!!
# KEY VALUES MUST BE ENCLOSED WITH DOUBLE QUOTES
# DOUBLE QUOTES INSIDE KEY VALUES MUST BE ESCAPED WITH \"
extContentMarkers:
  startExposedSection: "<!-- START_EXPOSED_SECTION -->"
  endExposedSection: "<!-- END_EXPOSED_SECTION -->"
pageToc:
  tocContainer: "#toc_container"
  toc: "#toc"
  tocLoadedEvent: "page_toc_loaded"
  scrollSpyBase: "body"
  tocItemLink: "#toc li a"
  tocItemLinkClass:
    light: "pageTocActiveLight"
    dark: "pageTocActiveDark"
  desktop:
    referenceContainer: ".main-content"
    offsetFromHeader: 35
    offsetFromReferenceContainer: 100
    leftSideBar: ".side-bar"
  pagesWithoutToc:
    - tag-info
    - cat-info
    - site-pages
colSchemaCorrections:
  elementsWithBackgroundAffected: "body, #category-menu-more-list, table, tbody, thead, tr, td, th, td[class=\"child\"], .offcanvas, .ck-editor__main, .side-bar, #hs-eu-cookie-confirmation"
  backgroundColorOnElementsAffected:
    light: "#fff"
    dark: "#0d1117" # HERE TO CHANGE DARK THEME BACKGROUND
  elementsWithTextAffected: "body, p, ul li, ol li, li a, h1, h2, span, .dt-info, label[for^=\"dt-length-\"], label[for^=\"dt-search-\"], #category-menu-more-list li a, .offcanvas-title, td, div[siteFunction=\"labelForPageSearchList\"], label[for=\"offcanvasPageFullInfoPageGeneralCustomNotesEdit\"]"
  textColorOnElementsAffected:
    light: "#000"
    dark: "#dee2e6"  # HERE TO CHANGE DARK THEME COLOR
  elementsWithBorderTopAffected: ".site-footer"
  borderTopOnElementsAffected:
    light: "1px solid #eeebee"
    dark: "1px solid #44434d"
  elementsWithBorderLeftAffected: ".main-header"
  borderLeftOnElementsAffected:
    light: "1px solid #44434d"
    dark: "1px solid #44434d"
  hideBodyUntilLoadTimeout: 200
goToTopBtn:
  topOfPageId: "#ihs_top_of_page"
  btnId: "#ihs_go_to_top_btn"
externalContent:
  containerToIncludeExternalContent: ".main-content main"
themeSwitch:
  cookie: "JTDThemeCookie"
  btnId: "themeSwitcher"
headerAboveContent:
  headerID: "#main-header"
  offsetWhenScroll: 20
layouts:
    contentArea:
      mainContainer: ".main-content-wrap"
      contentContainer: ".main-content main"
      contentWrapper: ".main-content"
    leftSideBar:
      container: ".side-bar"
toBeRemovedAfterLoad:
  - "script": # selector for the element to be removed, in the form of tag, .class, #id
    - "externalContent" # each selector[siteAttr = ...] will be removed
    - "page_var_init_script"
  - "h1":
    - "testAttr"
    - "testAttr_1"
catMenu: true
catMenuMoreBtn: "category-menu-more"
siteVars:
  siteTestBadge: "xxx"
similarByContent:
  maxPages: 4
hsIntegration:
  enabled: true
  bootstrapCSS: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  bootstrapJS: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  bootstrapIconsCSS: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
  forms:
    elements:
      fieldValidationErrorMessagesGroup: ".hs-error-msgs"
      formErrorMesage: ".hs_error_rollup"
      submittedMessage: ".submitted-message"
    submisionSource: 
      propName: "source"
      propValue: "figmares_doc_site"
scripts:
  jQuery: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
links:
  privacyLink: "https://innohub.space/eng/privacy"
  supportLink: "https://innohub.space/eng/mypmc/technical-support/"
selectedTextContextMenu:
  enabled: true
  minWords: 1
  maxWords: 10
