# HEADS UP!!!
# KEY VALUES MUST BE ENCLOSED WITH DOUBLE QUOTES
# DOUBLE QUOTES INSIDE KEY VALUES MUST BE ESCAPED WITH \"
extContentMarkers:
  startExposedSection: "<!-- START_EXPOSED_SECTION -->"
  endExposedSection: "<!-- END_EXPOSED_SECTION -->"
pageToc:
  tocContainer: "#toc_container"
  toc: "#toc"
  tocLoadedEvent: "page_toc_loaded"
  scrollSpyBase: "body"
  tocItemLink: "#toc li a"
  tocItemLinkClass:
    light: "pageTocActiveLight"
    dark: "pageTocActiveDark"
  desktop:
    referenceContainer: ".main-content"
    offsetFromHeader: 35
    offsetFromReferenceContainer: 100
    leftSideBar: ".side-bar"
  mobile:
    height: 300
  pagesWithoutToc:
    - tag-info
    - cat-info
    - site-pages
colSchemaCorrections:
  elementsWithBackgroundAffected: "body, #category-menu-more-list, table, tbody, thead, tr, td, th, td[class=\"child\"], .offcanvas, .ck-editor__main, .side-bar, #hs-eu-cookie-confirmation, #toc_mobile, .accordion-item, .accordion-header, .accordion-button"
  backgroundColorOnElementsAffected:
    light: "#fff"
    dark: "#0d1117" # HERE TO CHANGE DARK THEME BACKGROUND
  elementsWithTextAffected: "body, p, ul li, ol li, li a, h1, h2, span, .dt-info, label[for^=\"dt-length-\"], label[for^=\"dt-search-\"], #category-menu-more-list li a, .offcanvas-title, td, div[siteFunction=\"labelForPageSearchList\"], label[for=\"offcanvasPageFullInfoPageGeneralCustomNotesEdit\"], #toc_mobile, .accordion-item, .accordion-header, .accordion-button"
  textColorOnElementsAffected:
    light: "#000"
    dark: "#dee2e6"  # HERE TO CHANGE DARK THEME TEXT COLOR
  elementsWithBorderTopAffected: ".site-footer"
  borderTopOnElementsAffected:
    light: "1px solid #eeebee"
    dark: "1px solid #44434d"
  elementsWithBorderLeftAffected: ".main-header"
  borderLeftOnElementsAffected:
    light: "1px solid #44434d"
    dark: "1px solid #44434d"
  hideBodyUntilLoadTimeout: 0
goToTopBtn:
  topOfPageId: "#ihs_top_of_page"
  btnId: "#ihs_go_to_top_btn"
externalContent:
  containerToIncludeExternalContent: ".main-content main"
themeSwitch:
  cookie: "JTDThemeCookie"
  btnId: "themeSwitcher"
headerAboveContent:
  headerID: "#main-header"
  offsetWhenScroll: 20
layouts:
    contentArea:
      mainContainer: ".main-content-wrap"
      contentContainer: ".main-content main"
      contentWrapper: ".main-content"
    leftSideBar:
      container: ".side-bar"
      sideNav: "#site-nav"
      header: ".site-header"
      link: ".nav-list-link"
      siteTitle: ".site-title"
      mobileMenuBtnIcon: ".site-button-icon"
      mobileNavLinkExpander: ".page-with-children-expander"
toBeRemovedAfterLoad:
  - "script": # selector for the element to be removed, in the form of tag, .class, #id
    - "externalContent" # each selector[siteAttr = ...] will be removed
    - "init_not_needed_anymore"
    - "page_var_init_script"
  - "h1":
    - "testAttr"
    - "testAttr_1"
catMenu: true
catMenuMoreBtn: "category-menu-more"
siteVars:
  siteTestBadge: "xxx"
similarByContent:
  maxPages: 4
hsIntegration:
  enabled: true
  bootstrapCSS: "https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"
  bootstrapJS: "https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js"
  bootstrapIconsCSS: "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css"
  forms:
    elements:
      fieldValidationErrorMessagesGroup: ".hs-error-msgs"
      formErrorMesage: ".hs_error_rollup"
      submittedMessage: ".submitted-message"
    submisionSource: 
      propName: "source"
      propValue: "figmares_doc_site"
    prefLang:
      propName: "hs_language"
    userToken:
      propName: "subject"
scripts:
  jQuery: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
  fontFamily: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
links:
  privacyLink: "https://innohub.space/eng/privacy"
  supportLink: "https://innohub.space/eng/mypmc/technical-support/"
selectedTextContextMenu:
  enabled: true
  minWords: 1
  maxWords: 10
  comments:
    enabled: true
    maxChars: 250
    maxWords: 50
  tags:
    maxWords: 3
    maxChars: 20
user:
  userTokenCookie: "userToken"
savedItems:
  autoSaveBeforeLoad: true
multilang:
  enabled: true
  timeout: 1000
  scripts:
    i18: "https://cdn.jsdelivr.net/npm/i18next@24.2.1/i18next.min.js"
    i18Backend: "https://cdn.jsdelivr.net/npm/i18next-http-backend@3.0.1/i18nextHttpBackend.min.js"
    i18JQuery: "https://cdn.jsdelivr.net/npm/jquery-i18next@1.2.1/jquery-i18next.min.js"
    i18Sprintf: "https://cdn.jsdelivr.net/npm/i18next-sprintf-postprocessor@0.2.2/dist/umd/i18nextSprintfPostProcessor.min.js"
  availableLang: 
    - lang: "en" # ISO639-1 codes must be used / to be checked against Preferred Language(hs_language) Contact prop too if HS forms are used
      name: "English"
    - lang: "ro"
      name: "Rom√¢na"
    - lang: "sr"
      name: "Serbian"
  siteLanguage: 1
  fallbackLang: 0
  needsTranslation:
    - "body"
  dateFieldClass: "DSTcustomDateField"
  dateFieldSeparator: "-" # no space or : allowed
dataTables:
  TO_rebuildTableAfterUIInteration: 200 # i.e. after closing an offcanvas
  TO_afterAutoApplySearchPanesCurrentFilter: 500 # used in utilities.js, in $(document).ready(...) when creating datatable
  TO_resolveAutoApplySearchPanesCurrentFilter: 500 # used in utilities.js, createTable_ASYNC(...), helpers, autoApplyActiveFilter
  TO_doStuffAfterInitComplete: 100 # used in initComplete callback used in utilities.js, setDataTable(...), defaultSettings prop
  TO_forceSearchPanesToLoseFocus: 200 # used in utilities.js, createTable_ASYNC(...), helpers, clearActiveFilter
  TO_doStuffAfterSearchPanesContainerOpen: 100 # used in utilities.js, createTable_ASYNC, PROCESSING WHEN SEARCH PANES CONTAINER IS OPEN
  TO_doStuffAfterSearchPanesContainerClosed: 100 # used in utilities.js, createTable_ASYNC, PROCESSING WHEN SEARCH PANES CONTAINER IS CLOSED
  TO_resolvePromiseIncreateTable_ASYNC: 0 # used in utilities.js, createTable_ASYNC to resolve the promise returned by createTable_ASYNC
  TO_showLengthSearchInfoPagination: 0 # not used
  tableContainerFixedHeightWhenLoading: "200px"
  possibleDataTableParents: [".table-wrapper", ".card-body"] # used in utilities.js, setDataTable/defaultSettings/initComplete