name: Copy gh-pages Branch from figma repo to jekyll-site-template repository

on:
    workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: pmc-comunity/figma
          ref: gh-pages

      - name: Copy contents to destination repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add destination https://github.com/pmc-comunity/jekyl-site-template.git
          git fetch destination
          git checkout -b main destination/main || git checkout --orphan main
          git rm -rf .
          cp -r . ../temp
          cd ../temp
          cp -r . ../source-repo
          cd ../source-repo
          git add .
          git commit -m "Update from gh-pages branch of pcm-comunity/figma repository"
          git push -f destination main

      - name: Clean up
        run: |
          rm -rf ../temp
          rm -rf ../source-repo