name: Copy gh-pages to jekyll-site-template repo

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: pmc-community/figma
          ref: gh-pages

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_TO_DEPLOY_TO_JEKYLL_SITE_TEMPLATE }}

      - name: Push changes to destination repository
        run: |
          git config user.email "florin-hoinarescu@yahoo.com"
          git config user.name "florinhoinarescu"
          git pull --rebase git@github.com:pmc-community/jekyll-site-template.git
          git push git@github.com:pmc-community/jekyll-site-template.git HEAD:refs/heads/main --force