name: Copy gh-pages to jekyll-site-template repo

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: username/sourceRepo
          ref: branchX

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_TO_DEPLOY_TO_JEKYLL_SITE_TEMPLATE }}

      - name: Push changes to destination repository
        run: |
          git remote add destination git@github.com:pmc-community/jekyll-site-template.git
          git fetch origin
          git merge origin/main
          git push -f origin main